### ISSUE TITLE
dead-simple-jekyll-comments

### ISSUE THREAD

**Issue by BitBegginer** [aioobe/dead-simple-jekyll-comments#1]
Hello!

Sorry for trivial question, but I'm beginner on git pages and need help.
My local test was correct. but how to run it on bitbucket? Problem is with "Submit" button and event.

**Comment by aioobe** [comment]
Unless you pay for Bitbucket (and have access to pipelines) you can't _run_ anything on Bitbucket. You'll have to host the webhook yourself somehow. On a VPS or a Raspberry Pi or something.

The reason the README says it "works on Bitbucket" is simply because StaticMan _only_ supports GitHub.
